sudo: required
dist: trusty
language: cpp
cache: apt
compiler:
- gcc
- clang
before_script:
- apt-get update -qq
- apt-get install -qq nasm
script:
- mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make -j2
notifications:
  slack:
    secure: g1Nm7C7TYKg4RjDJ5cwuEcgKXfOAmVOu51adTPLBLGzZcCbCrkwQgI39ZycsalaACSnC8iNvqSCbRfZIA5mkDZ7VADaiZgLoWjq3RQzJmWgwGhhtyRkbtiicBnowTL5hIEiMOv6RnKlbB7M2OwzRiS07+FQXrK24hz+qm6zPptw=
