language: cpp
cache: apt
compiler:
- gcc
- clang

# for packaging only
#install:
#- gem install fpm

before_script:

# repos
- sudo add-apt-repository ppa:kalakris/cmake -y
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- if [ "$CXX" = "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -; fi
- if [ "$CXX" = "clang++" ]; then sudo apt-add-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'; fi
- sudo apt-get -qq update

# cmake-2.8.8+ is required
- sudo apt-get install -qq cmake nasm g++-4.8-multilib
# for packaging only
# - sudo apt-get install rpm ruby-dev

# gcc-4.8
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi

# clang-3.5
- if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
- if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq clang-3.5; fi
- if [ "$CXX" = "clang++" ]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.5 90; fi
- if [ "$CXX" = "clang++" ]; then sudo rm /usr/local/clang-3.4/bin/clang++; fi

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make -j2

notifications:
  slack:
    secure: gg6IfwUAM+3Ih2aoxq9EfOdR4RAc9or4O2b01L4HNX4Qq4erud6VIeanwS696qR9/v7jQXqqEOwhGa2FnUBPAK7DDSwSqYOhEFclRKfea4zEGnAsZu1yFDVE17KjQNgBUpDHC+n3TCfYC4MSzSs9T6zQhwi0mNCuAtnHjjktR+4=

env:
  global:
  - secure: "EqeaUi97HPVQJtbUsaJwCp3nzcRnMlt+CDcXygNBNz1CFIHxte+CqLhTKi270PVCBmp0s5oomx2/TUY1aIIXkcBdbXT28xkTRJ83wjcd5lkwCHPo8KP+azhL5DqHDAw6RbpWoXRi1HL1+K0acCf9ZIUfs2mQmyKdW8L/GgJZHgg="
addons:
  coverity_scan:
    project:
      name: "trailofbits/mcsema"
      description: "x86 to machine code translation framework"
    notification_email: dan@trailofbits.com
    build_command_prepend: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .."
    build_command: "make -j2"
    branch_pattern: master
